### ISSUE TITLE
JAVA_HOME

### ISSUE THREAD

**Issue by alkersan** [dockerfile/java#11]
Hi. While playing with simple hadoop cluster setup inside docker containers, I noticed that lots of other software (not only hadoop) relies on $JAVA_HOME variable.
And while this build is responsible for java flavor installation, wouldn't it be reasonable to define JAVA_HOME in Dockerfile via ENV command, for further use?

My thoughts relies on [best practices](https://docs.docker.com/articles/dockerfile_best-practices/#env), where ENV  usage is proper for "providing variables specific for containterized service"

**Comment by pilwon** [comment]
@alkersan That's a great idea. Could you submit a PR for this? Thanks.

**Comment by XiaoCao1434** [comment]
it's importent to deal ENVI,I think at last.
