### ISSUE TITLE
java:oracle-java8 not found

### ISSUE THREAD

**Issue by Jamarilo** [dockerfile/java#19]
Hi i can not pull an Image form java:oracle-java8

Unable to find image 'dockerfile/java:oracle-java8' locally
Pulling repository dockerfile/java
FATA[0003] Error: image dockerfile/java:oracle-java8 not found

thanks for your help

**Comment by jniesen** [comment]
We're getting the same thing for java:oracle-java7

``` shell
sudo docker run -it --rm dockerfile/java:oracle-java7 java -version
Unable to find image 'dockerfile/java:oracle-java7' locally
Pulling repository dockerfile/java
2015/05/06 19:54:28 HTTP code: 404
```

**Comment by kennyg** [comment]
@jniesen it looks to be related to this post: https://forums.docker.com/t/dockerfile-java-oracle-java7-repo-not-found-issue/1472/2 . it seems the dockerfile repo's been migrated, and in the process the oracle java image has been removed or otherwise gone missing.

**Comment by Jamarilo** [comment]
@kennyg thanks a lot you're right they have moved this repo to an offical Dockerhub:

http://blog.docker.com/2015/03/updates-available-to-popular-repos-update-your-images/

**Comment by scf37** [comment]
So, they deleted all oracle java images. Who uses openjdk in production, seriously?
Edit: just wanted to say thanks for breaking our Dockerfiles that depend on dockerfile/java:oracle-java8

**Comment by Jamarilo** [comment]
No one uses openjedk in production.... you can say thanks to Oracle. I have create my own Ubuntu Base with Oracle-java installed on it...

**Comment by acidghost** [comment]
So.. How can the problem be solved?

I'm new to docker..

Edit: resolved replacing `dockerfile/java` with `java:7`

**Comment by gurusharma08** [comment]
docker search java:java8
 repository command in ur docker vm

**Comment by danktec** [comment]
docker pull openjdk:8

FROM openjdk:8
