### ISSUE TITLE
bash: javac: command not found

### ISSUE THREAD

**Issue by wangyujingGH** [dockerfile/java#30]
According the steps to build the java image, then `docker run -it [name] javac`,  "docker: Error response from daemon: Container command 'javac' not found or does not exist..", what's wrong?

**Comment by Richard-Mathie** [comment]
`update-alternatives --set javac $JAVA_HOME/bin/javac`

**Comment by wangyujingGH** [comment]
'update-alternatives --set javac $JAVA_HOME/bin/javac' doesn't work.
According others resource, 'sudo apt-get install openjdk-7-jre' only installs the Java Runtime Environment, which contains the implemetion of 'java' command but not the 'javac'.
So running 'sudo apt-get install openjdk-7-jdk' installs the Java Development Environment.
